name: Deploy to Cloudflare Pages & PR Preview

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1

      - name: Install Node dependencies
        run: npm install tailwindcss @tailwindcss/cli playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Build CSS
        run: npx @tailwindcss/cli -i main.css -o dist/build.css -m

      - name: Build SSG
        run: deno task build

      - name: Deploy to Cloudflare Pages Production
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ secrets.CF_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITTOKEN }}

      - name: Deploy to Cloudflare Pages Preview
        id: deploy-preview
        if: github.event_name == 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ secrets.CF_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITTOKEN }}

      - name: Print Deployment URL
        if: github.event_name == 'pull_request'
        env:
          DEPLOYMENT_URL: ${{ steps.deploy-preview.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL